#!/usr/bin/env bash
# ==============================================================================
# Google Cloud Model Armor - 1-Click Cloud Shell Deployer
# Generated by Agentic AISPR Engine
# Target Project: test-enterprise-ai (Region: us-central1)
# Date: 2026-09-02T18:38:14.514779Z
# ==============================================================================
set -euo pipefail

PROJECT_ID="test-enterprise-ai"
LOCATION="us-central1"
TEMPLATE_ID="secops-guardrail-prod"

echo "======================================================================"
echo " 🛡️  Deploying Google Cloud Model Armor to $PROJECT_ID ($LOCATION)"
echo "======================================================================"

export CLOUDSDK_CONTEXT_AWARE_USE_CLIENT_CERTIFICATE=false
export CLOUDSDK_CONTEXT_AWARE_USE_ECP_HTTP_PROXY=false

# 1. Enable APIs
echo "[+] Step 1/4: Enabling modelarmor.googleapis.com, dlp.googleapis.com, logging.googleapis.com..."
gcloud services enable modelarmor.googleapis.com dlp.googleapis.com logging.googleapis.com monitoring.googleapis.com --project="$PROJECT_ID"

# 2. IAM Configuration
ACTIVE_USER="$(gcloud config get-value account 2>/dev/null || echo '')"
if [[ -n "$ACTIVE_USER" ]]; then
  echo "[+] Step 2/4: Granting roles/modelarmor.admin to $ACTIVE_USER..."
  gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="user:$ACTIVE_USER" \
    --role="roles/modelarmor.admin" \
    --quiet >/dev/null 2>&1 || true
fi

TOKEN="$(gcloud auth print-access-token)"

# 3. Apply Global FloorSetting
echo "[+] Step 3/4: Enforcing Non-Burlable Global FloorSetting in $PROJECT_ID..."
curl -s -X PATCH \
  -H "Authorization: Bearer $TOKEN" \
  -H "X-Goog-User-Project: $PROJECT_ID" \
  -H "Content-Type: application/json" \
  "https://modelarmor.googleapis.com/v1/projects/$PROJECT_ID/locations/global/floorSetting?updateMask=filterConfig,enableFloorSettingEnforcement" \
  -d '{
    "enableFloorSettingEnforcement": true,
    "filterConfig": {
      "raiSettings": {
        "raiFilters": [
          {"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}
        ]
      },
      "piAndJailbreakFilterSettings": {
        "filterEnforcement": "ENABLED",
        "confidenceLevel": "MEDIUM_AND_ABOVE"
      },
      "maliciousUriFilterSettings": {
        "filterEnforcement": "ENABLED"
      }
    }
  }' >/dev/null

# 4. Provision Guardrail Template
echo "[+] Step 4/4: Provisioning Guardrail Template '$TEMPLATE_ID' in $LOCATION..."
curl -s -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "X-Goog-User-Project: $PROJECT_ID" \
  -H "Content-Type: application/json" \
  "https://modelarmor.$LOCATION.rep.googleapis.com/v1/projects/$PROJECT_ID/locations/$LOCATION/templates?templateId=$TEMPLATE_ID" \
  -d '{
    "filterConfig": {
      "raiSettings": {
        "raiFilters": [
          {"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
          {"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}
        ]
      },
      "piAndJailbreakFilterSettings": {
        "filterEnforcement": "ENABLED",
        "confidenceLevel": "LOW_AND_ABOVE"
      },
      "maliciousUriFilterSettings": {
        "filterEnforcement": "ENABLED"
      }
    },
    "templateMetadata": {
      "logSanitizeOperations": true,
      "customPromptSafetyErrorMessage": "Prompt blocked by Model Armor security guardrail.",
      "customPromptSafetyErrorCode": 400
    }
  }' >/dev/null

echo "======================================================================"
echo "🎉 MODEL ARMOR DEPLOYMENT COMPLETED SUCCESSFULLY IN $PROJECT_ID!"
echo "   Guardrail Template: projects/$PROJECT_ID/locations/$LOCATION/templates/$TEMPLATE_ID"
echo "======================================================================"
