# ==============================================================================
# Google Cloud Model Armor - Production Security Perimeter
# Generated by Agentic AISPR (Constructive Implementation Engine)
# Project Scope: test-enterprise-ai (Region: us-central1)
# Date: 2026-09-01T23:44:23.518736Z
# ==============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.2.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.location
}

# 1. Enable Required GCP APIs
resource "google_project_service" "modelarmor_api" {
  project            = var.project_id
  service            = "modelarmor.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "dlp_api" {
  project            = var.project_id
  service            = "dlp.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "logging_api" {
  project            = var.project_id
  service            = "logging.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "monitoring_api" {
  project            = var.project_id
  service            = "monitoring.googleapis.com"
  disable_on_destroy = false
}

# 2. Cloud DLP Inspection Template (Sensitive Data & PII)
resource "google_data_loss_prevention_inspect_template" "aispr_dlp_inspect" {
  count        = var.enable_dlp_integration ? 1 : 0
  parent       = "projects/${var.project_id}/locations/global"
  description  = "AISPR Automated DLP Inspection Template for Generative AI & Model Armor"
  display_name = "aispr-ai-dlp-inspect-template"

  inspect_config {
    info_types { name = "BRAZIL_CPF_NUMBER" }
    info_types { name = "US_SOCIAL_SECURITY_NUMBER" }
    info_types { name = "CREDIT_CARD_NUMBER" }
    info_types { name = "PHONE_NUMBER" }
    info_types { name = "EMAIL_ADDRESS" }
    info_types { name = "AUTH_TOKEN" }
    info_types { name = "GCP_CREDENTIALS" }
    info_types { name = "JSON_WEB_TOKEN" }
    info_types { name = "GENERIC_API_KEY" }

    min_likelihood = "LIKELY"
    include_quote  = true

    limits {
      max_findings_per_item    = 100
      max_findings_per_request = 0
    }
  }

  depends_on = [google_project_service.dlp_api]
}

# 3. Model Armor Global FloorSetting Provisioning (Non-burlable baseline)
resource "null_resource" "model_armor_floor_setting" {
  count = var.enable_floor_setting ? 1 : 0

  triggers = {
    project_id = var.project_id
    enforce    = var.enable_floor_setting
  }

  provisioner "local-exec" {
    command = <<-EOT
      TOKEN=$(gcloud auth print-access-token)
      curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "X-Goog-User-Project: ${var.project_id}" -H "Content-Type: application/json" \
        "https://modelarmor.googleapis.com/v1/projects/${var.project_id}/locations/global/floorSetting?updateMask=filterConfig,enableFloorSettingEnforcement" \
        -d '{
          "enableFloorSettingEnforcement": true,
          "filterConfig": {
            "raiSettings": {
              "raiFilters": [
                {"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}
              ]
            },
            "piAndJailbreakFilterSettings": {
              "filterEnforcement": "ENABLED",
              "confidenceLevel": "MEDIUM_AND_ABOVE"
            },
            "maliciousUriFilterSettings": {
              "filterEnforcement": "ENABLED"
            }
          }
        }'
    EOT
  }

  depends_on = [google_project_service.modelarmor_api]
}

# 4. Model Armor Guardrail Template Provisioning
resource "null_resource" "model_armor_template" {
  triggers = {
    project_id  = var.project_id
    location    = var.location
    template_id = var.template_id
  }

  provisioner "local-exec" {
    command = <<-EOT
      TOKEN=$(gcloud auth print-access-token)
      curl -s -X POST -H "Authorization: Bearer $TOKEN" -H "X-Goog-User-Project: ${var.project_id}" -H "Content-Type: application/json" \
        "https://modelarmor.${var.location}.rep.googleapis.com/v1/projects/${var.project_id}/locations/${var.location}/templates?templateId=${var.template_id}" \
        -d '{
          "filterConfig": {
            "raiSettings": {
              "raiFilters": [
                {"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                {"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}
              ]
            },
            "piAndJailbreakFilterSettings": {
              "filterEnforcement": "ENABLED",
              "confidenceLevel": "LOW_AND_ABOVE"
            },
            "maliciousUriFilterSettings": {
              "filterEnforcement": "ENABLED"
            }
          },
          "templateMetadata": {
            "logSanitizeOperations": true,
            "customPromptSafetyErrorMessage": "Prompt blocked by Model Armor security guardrail.",
            "customPromptSafetyErrorCode": 400,
            "customLlmResponseSafetyErrorMessage": "Model completion blocked by Model Armor security guardrail.",
            "customLlmResponseSafetyErrorCode": 400
          },
          "labels": {
            "managed-by": "aispr-terraform",
            "framework": "google-saif-nist-ai-rmf"
          }
        }'
    EOT
  }

  depends_on = [google_project_service.modelarmor_api, null_resource.model_armor_floor_setting]
}
