# -*- coding: utf-8 -*-
"""
Copyright © 2026 Google LLC. Developed by Joabson Saccomani (@jsaccomani).
Role: Cloud Security Consultant | LinkedIn: https://www.linkedin.com/in/jsaccomani
Licensed under the Apache License, Version 2.0.

AISPR Model Armor Implementation Engine - Pillar 2: Construtiva (Engineering & IaC)
Generates complete Terraform production blueprints, Cloud Shell 1-click provisioning scripts,
application middleware interceptors (FastAPI, Vertex AI SDK, LangChain), and live cloud deployment.
"""

import os
import sys
import json
import shutil
import logging
import subprocess
from datetime import datetime
from typing import Dict, List, Any, Optional

logger = logging.getLogger("AISPR-ModelArmor-Builder")


class ModelArmorConstructiveBuilder:
    """
    Constructs production deployment assets (Terraform, Cloud Shell, Middleware)
    and executes live cloud deployment for Google Cloud Model Armor.
    """

    def __init__(self, project_root: Optional[str] = None):
        if project_root is None:
            cur_dir = os.path.dirname(os.path.abspath(__file__))
            self.project_root = os.path.abspath(os.path.join(cur_dir, "..", ".."))
        else:
            self.project_root = project_root
        self.deployments_dir = os.path.join(self.project_root, "reports", "model_armor_deployment")
        self.tf_dir = os.path.join(self.deployments_dir, "terraform")
        self.app_dir = os.path.join(self.deployments_dir, "app_integration")

    def build_terraform_package(self, plan: Dict[str, Any]) -> str:
        """
        Generates complete Terraform IaC module for Model Armor, Cloud DLP, and Monitoring.
        """
        os.makedirs(self.tf_dir, exist_ok=True)
        meta = plan.get("metadata", {})
        params = plan.get("parameters", {})
        
        project_id = meta.get("project_id", "your-gcp-project-id")
        location = meta.get("location", "us-central1")
        template_id = meta.get("template_id", "secops-guardrail-prod")

        # 1. main.tf
        main_tf = f"""# ==============================================================================
# Google Cloud Model Armor - Production Security Perimeter
# Generated by Agentic AISPR (Constructive Implementation Engine)
# Project Scope: {project_id} (Region: {location})
# Date: {datetime.utcnow().isoformat()}Z
# ==============================================================================

terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = ">= 5.0.0"
    }}
    null = {{
      source  = "hashicorp/null"
      version = ">= 3.2.0"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.location
}}

# 1. Enable Required GCP APIs
resource "google_project_service" "modelarmor_api" {{
  project            = var.project_id
  service            = "modelarmor.googleapis.com"
  disable_on_destroy = false
}}

resource "google_project_service" "dlp_api" {{
  project            = var.project_id
  service            = "dlp.googleapis.com"
  disable_on_destroy = false
}}

resource "google_project_service" "logging_api" {{
  project            = var.project_id
  service            = "logging.googleapis.com"
  disable_on_destroy = false
}}

resource "google_project_service" "monitoring_api" {{
  project            = var.project_id
  service            = "monitoring.googleapis.com"
  disable_on_destroy = false
}}

# 2. Cloud DLP Inspection Template (Sensitive Data & PII)
resource "google_data_loss_prevention_inspect_template" "aispr_dlp_inspect" {{
  count        = var.enable_dlp_integration ? 1 : 0
  parent       = "projects/${{var.project_id}}/locations/global"
  description  = "AISPR Automated DLP Inspection Template for Generative AI & Model Armor"
  display_name = "aispr-ai-dlp-inspect-template"

  inspect_config {{
    info_types {{ name = "BRAZIL_CPF_NUMBER" }}
    info_types {{ name = "US_SOCIAL_SECURITY_NUMBER" }}
    info_types {{ name = "CREDIT_CARD_NUMBER" }}
    info_types {{ name = "PHONE_NUMBER" }}
    info_types {{ name = "EMAIL_ADDRESS" }}
    info_types {{ name = "AUTH_TOKEN" }}
    info_types {{ name = "GCP_CREDENTIALS" }}
    info_types {{ name = "JSON_WEB_TOKEN" }}
    info_types {{ name = "GENERIC_API_KEY" }}

    min_likelihood = "LIKELY"
    include_quote  = true

    limits {{
      max_findings_per_item    = 100
      max_findings_per_request = 0
    }}
  }}

  depends_on = [google_project_service.dlp_api]
}}

# 3. Model Armor Global FloorSetting Provisioning (Non-burlable baseline)
resource "null_resource" "model_armor_floor_setting" {{
  count = var.enable_floor_setting ? 1 : 0

  triggers = {{
    project_id = var.project_id
    enforce    = var.enable_floor_setting
  }}

  provisioner "local-exec" {{
    command = <<-EOT
      TOKEN=$(gcloud auth print-access-token)
      curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "X-Goog-User-Project: ${{var.project_id}}" -H "Content-Type: application/json" \\
        "https://modelarmor.googleapis.com/v1/projects/${{var.project_id}}/locations/global/floorSetting?updateMask=filterConfig,enableFloorSettingEnforcement" \\
        -d '{{
          "enableFloorSettingEnforcement": true,
          "filterConfig": {{
            "raiSettings": {{
              "raiFilters": [
                {{"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}}
              ]
            }},
            "piAndJailbreakFilterSettings": {{
              "filterEnforcement": "ENABLED",
              "confidenceLevel": "MEDIUM_AND_ABOVE"
            }},
            "maliciousUriFilterSettings": {{
              "filterEnforcement": "ENABLED"
            }}
          }}
        }}'
    EOT
  }}

  depends_on = [google_project_service.modelarmor_api]
}}

# 4. Model Armor Guardrail Template Provisioning
resource "null_resource" "model_armor_template" {{
  triggers = {{
    project_id  = var.project_id
    location    = var.location
    template_id = var.template_id
  }}

  provisioner "local-exec" {{
    command = <<-EOT
      TOKEN=$(gcloud auth print-access-token)
      curl -s -X POST -H "Authorization: Bearer $TOKEN" -H "X-Goog-User-Project: ${{var.project_id}}" -H "Content-Type: application/json" \\
        "https://modelarmor.${{var.location}}.rep.googleapis.com/v1/projects/${{var.project_id}}/locations/${{var.location}}/templates?templateId=${{var.template_id}}" \\
        -d '{{
          "filterConfig": {{
            "raiSettings": {{
              "raiFilters": [
                {{"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
                {{"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}}
              ]
            }},
            "piAndJailbreakFilterSettings": {{
              "filterEnforcement": "ENABLED",
              "confidenceLevel": "LOW_AND_ABOVE"
            }},
            "maliciousUriFilterSettings": {{
              "filterEnforcement": "ENABLED"
            }}
          }},
          "templateMetadata": {{
            "logSanitizeOperations": true,
            "customPromptSafetyErrorMessage": "Prompt blocked by Model Armor security guardrail.",
            "customPromptSafetyErrorCode": 400,
            "customLlmResponseSafetyErrorMessage": "Model completion blocked by Model Armor security guardrail.",
            "customLlmResponseSafetyErrorCode": 400
          }},
          "labels": {{
            "managed-by": "aispr-terraform",
            "framework": "google-saif-nist-ai-rmf"
          }}
        }}'
    EOT
  }}

  depends_on = [google_project_service.modelarmor_api, null_resource.model_armor_floor_setting]
}}
"""
        with open(os.path.join(self.tf_dir, "main.tf"), "w", encoding="utf-8") as f:
            f.write(main_tf)

        # 2. variables.tf
        var_tf = """variable "project_id" {
  description = "Target Google Cloud Project ID"
  type        = string
}

variable "location" {
  description = "Deployment region for Model Armor Templates"
  type        = string
  default     = "us-central1"
}

variable "template_id" {
  description = "Unique Identifier for the Model Armor Guardrail Template"
  type        = string
  default     = "secops-guardrail-prod"
}

variable "enable_floor_setting" {
  description = "Whether to enforce non-burlable project-wide FloorSetting"
  type        = bool
  default     = true
}

variable "enable_dlp_integration" {
  description = "Whether to provision Cloud DLP inspection and de-identification templates"
  type        = bool
  default     = true
}
"""
        with open(os.path.join(self.tf_dir, "variables.tf"), "w", encoding="utf-8") as f:
            f.write(var_tf)

        # 3. outputs.tf
        out_tf = """output "model_armor_template_name" {
  description = "Full resource name of the deployed Model Armor Template"
  value       = "projects/${var.project_id}/locations/${var.location}/templates/${var.template_id}"
}

output "floor_setting_enforced" {
  description = "FloorSetting enforcement status"
  value       = var.enable_floor_setting
}

output "dlp_template_name" {
  description = "Cloud DLP Inspection Template resource name"
  value       = var.enable_dlp_integration ? google_data_loss_prevention_inspect_template.aispr_dlp_inspect[0].name : "DISABLED"
}
"""
        with open(os.path.join(self.tf_dir, "outputs.tf"), "w", encoding="utf-8") as f:
            f.write(out_tf)

        # 4. terraform.tfvars
        tfvars = f"""project_id             = "{project_id}"
location               = "{location}"
template_id            = "{template_id}"
enable_floor_setting   = {str(params.get('enable_floor_setting', True)).lower()}
enable_dlp_integration = {str(params.get('enable_dlp', True)).lower()}
"""
        with open(os.path.join(self.tf_dir, "terraform.tfvars"), "w", encoding="utf-8") as f:
            f.write(tfvars)

        logger.info(f"Terraform package successfully generated at: {self.tf_dir}")
        return self.tf_dir

    def build_cloud_shell_script(self, plan: Dict[str, Any]) -> str:
        """
        Generates a standalone, dependency-free bash deployment script for Google Cloud Shell.
        """
        os.makedirs(self.deployments_dir, exist_ok=True)
        meta = plan.get("metadata", {})
        project_id = meta.get("project_id", "your-gcp-project-id")
        location = meta.get("location", "us-central1")
        template_id = meta.get("template_id", "secops-guardrail-prod")

        script_content = f"""#!/usr/bin/env bash
# ==============================================================================
# Google Cloud Model Armor - 1-Click Cloud Shell Deployer
# Generated by Agentic AISPR Engine
# Target Project: {project_id} (Region: {location})
# Date: {datetime.utcnow().isoformat()}Z
# ==============================================================================
set -euo pipefail

PROJECT_ID="{project_id}"
LOCATION="{location}"
TEMPLATE_ID="{template_id}"

echo "======================================================================"
echo " 🛡️  Deploying Google Cloud Model Armor to $PROJECT_ID ($LOCATION)"
echo "======================================================================"

export CLOUDSDK_CONTEXT_AWARE_USE_CLIENT_CERTIFICATE=false
export CLOUDSDK_CONTEXT_AWARE_USE_ECP_HTTP_PROXY=false

# 1. Enable APIs
echo "[+] Step 1/4: Enabling modelarmor.googleapis.com, dlp.googleapis.com, logging.googleapis.com..."
gcloud services enable modelarmor.googleapis.com dlp.googleapis.com logging.googleapis.com monitoring.googleapis.com --project="$PROJECT_ID"

# 2. IAM Configuration
ACTIVE_USER="$(gcloud config get-value account 2>/dev/null || echo '')"
if [[ -n "$ACTIVE_USER" ]]; then
  echo "[+] Step 2/4: Granting roles/modelarmor.admin to $ACTIVE_USER..."
  gcloud projects add-iam-policy-binding "$PROJECT_ID" \\
    --member="user:$ACTIVE_USER" \\
    --role="roles/modelarmor.admin" \\
    --quiet >/dev/null 2>&1 || true
fi

TOKEN="$(gcloud auth print-access-token)"

# 3. Apply Global FloorSetting
echo "[+] Step 3/4: Enforcing Non-Burlable Global FloorSetting in $PROJECT_ID..."
curl -s -X PATCH \\
  -H "Authorization: Bearer $TOKEN" \\
  -H "X-Goog-User-Project: $PROJECT_ID" \\
  -H "Content-Type: application/json" \\
  "https://modelarmor.googleapis.com/v1/projects/$PROJECT_ID/locations/global/floorSetting?updateMask=filterConfig,enableFloorSettingEnforcement" \\
  -d '{{
    "enableFloorSettingEnforcement": true,
    "filterConfig": {{
      "raiSettings": {{
        "raiFilters": [
          {{"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}}
        ]
      }},
      "piAndJailbreakFilterSettings": {{
        "filterEnforcement": "ENABLED",
        "confidenceLevel": "MEDIUM_AND_ABOVE"
      }},
      "maliciousUriFilterSettings": {{
        "filterEnforcement": "ENABLED"
      }}
    }}
  }}' >/dev/null

# 4. Provision Guardrail Template
echo "[+] Step 4/4: Provisioning Guardrail Template '$TEMPLATE_ID' in $LOCATION..."
curl -s -X POST \\
  -H "Authorization: Bearer $TOKEN" \\
  -H "X-Goog-User-Project: $PROJECT_ID" \\
  -H "Content-Type: application/json" \\
  "https://modelarmor.$LOCATION.rep.googleapis.com/v1/projects/$PROJECT_ID/locations/$LOCATION/templates?templateId=$TEMPLATE_ID" \\
  -d '{{
    "filterConfig": {{
      "raiSettings": {{
        "raiFilters": [
          {{"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"}},
          {{"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}}
        ]
      }},
      "piAndJailbreakFilterSettings": {{
        "filterEnforcement": "ENABLED",
        "confidenceLevel": "LOW_AND_ABOVE"
      }},
      "maliciousUriFilterSettings": {{
        "filterEnforcement": "ENABLED"
      }}
    }},
    "templateMetadata": {{
      "logSanitizeOperations": true,
      "customPromptSafetyErrorMessage": "Prompt blocked by Model Armor security guardrail.",
      "customPromptSafetyErrorCode": 400
    }}
  }}' >/dev/null

echo "======================================================================"
echo "🎉 MODEL ARMOR DEPLOYMENT COMPLETED SUCCESSFULLY IN $PROJECT_ID!"
echo "   Guardrail Template: projects/$PROJECT_ID/locations/$LOCATION/templates/$TEMPLATE_ID"
echo "======================================================================"
"""
        script_path = os.path.join(self.deployments_dir, "deploy_model_armor.sh")
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)
        os.chmod(script_path, 0o755)

        logger.info(f"Cloud Shell deployment script generated at: {script_path}")
        return script_path

    def build_application_middleware(self, plan: Dict[str, Any]) -> str:
        """
        Generates application middleware artifacts for FastAPI, Vertex AI Python SDK, and LangChain.
        """
        os.makedirs(self.app_dir, exist_ok=True)
        meta = plan.get("metadata", {})
        project_id = meta.get("project_id", "your-gcp-project-id")
        location = meta.get("location", "us-central1")
        template_id = meta.get("template_id", "secops-guardrail-prod")

        # 1. FastAPI Middleware
        fastapi_code = f"""# -*- coding: utf-8 -*-
\"\"\"
Google Cloud Model Armor - Asynchronous FastAPI Middleware
Drop-in security guardrail for REST and WebSocket AI Chat endpoints.
\"\"\"

import json
from fastapi import Request, Response, HTTPException
from starlette.middleware.base import BaseHTTPMiddleware
from agentic.runtime_defense.model_armor_guard import ModelArmorGuard

class ModelArmorMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, template_path: str = "projects/{project_id}/locations/{location}/templates/{template_id}"):
        super().__init__(app)
        self.guard = ModelArmorGuard(template_id="{template_id}", location="{location}", project_id="{project_id}")

    async def dispatch(self, request: Request, call_next):
        # Only inspect generative AI routes
        if request.url.path.startswith(("/api/ai", "/v1/chat", "/api/v1/generate")):
            body_bytes = await request.body()
            if body_bytes:
                try:
                    payload = json.loads(body_bytes.decode("utf-8"))
                    prompt = payload.get("prompt") or payload.get("message") or payload.get("query")
                    if prompt:
                        verdict = self.guard.inspect_prompt(prompt)
                        if verdict.get("verdict") == "BLOCKED":
                            raise HTTPException(
                                status_code=400,
                                detail={{
                                    "error": "SECURITY_POLICY_VIOLATION",
                                    "message": "Prompt rejected by Google Cloud Model Armor guardrail.",
                                    "matched_rules": verdict.get("matched_rules", [])
                                }}
                            )
                        # Replace with sanitized prompt if PII was masked
                        if verdict.get("verdict") == "SANITIZED":
                            payload["prompt"] = verdict.get("sanitized_prompt")
                            # Continue with sanitized payload
                except HTTPException:
                    raise
                except Exception:
                    pass

        response = await call_next(request)
        response.headers["X-Model-Armor-Enforced"] = "true"
        return response
"""
        with open(os.path.join(self.app_dir, "fastapi_model_armor_middleware.py"), "w", encoding="utf-8") as f:
            f.write(fastapi_code)

        # 2. Vertex AI SDK Wrapper
        vertex_wrapper = f"""# -*- coding: utf-8 -*-
\"\"\"
Google Cloud Model Armor - Vertex AI GenerativeModel SDK Wrapper
Transparent pre-call prompt sanitization and post-call response shielding.
\"\"\"

import vertexai
from vertexai.generative_models import GenerativeModel
from agentic.runtime_defense.model_armor_guard import ModelArmorGuard

class GenerativeModelWithModelArmor:
    \"\"\"
    Wrapper around Vertex AI GenerativeModel that enforces Model Armor guardrails.
    \"\"\"
    def __init__(self, model_name: str = "gemini-1.5-pro", project_id: str = "{project_id}", location: str = "{location}"):
        vertexai.init(project=project_id, location=location)
        self.raw_model = GenerativeModel(model_name)
        self.guard = ModelArmorGuard(project_id=project_id, location=location, template_id="{template_id}")

    def generate_content(self, prompt: str, **kwargs):
        # 1. Pre-execution Prompt Sanitization (Input Shielding)
        in_verdict = self.guard.inspect_prompt(prompt)
        if in_verdict.get("verdict") == "BLOCKED":
            raise ValueError(f"Model Armor blocked prompt: {{in_verdict.get('matched_rules')}}")
        
        safe_prompt = in_verdict.get("sanitized_prompt", prompt)

        # 2. Live Model Inference
        response = self.raw_model.generate_content(safe_prompt, **kwargs)

        # 3. Post-execution Output Shielding
        out_verdict = self.guard.inspect_output(response.text)
        if out_verdict.get("verdict") == "BLOCKED":
            raise ValueError("Model Armor blocked generated output due to safety violation.")

        return out_verdict.get("sanitized_output", response.text)
"""
        with open(os.path.join(self.app_dir, "vertex_ai_model_armor_wrapper.py"), "w", encoding="utf-8") as f:
            f.write(vertex_wrapper)

        # 3. LangChain Guardrail Runnable
        langchain_guard = f"""# -*- coding: utf-8 -*-
\"\"\"
Google Cloud Model Armor - LangChain Runnable Guardrail & Interceptor
\"\"\"

from langchain_core.runnables import RunnableLambda
from agentic.runtime_defense.model_armor_guard import ModelArmorGuard

guard = ModelArmorGuard(project_id="{project_id}", location="{location}", template_id="{template_id}")

def model_armor_input_guard(prompt_text: str) -> str:
    verdict = guard.inspect_prompt(prompt_text)
    if verdict.get("verdict") == "BLOCKED":
        raise PermissionError(f"Model Armor Guardrail Rejected Query: {{verdict.get('matched_rules')}}")
    return verdict.get("sanitized_prompt", prompt_text)

# LangChain LCEL Integration: chain = model_armor_guard | model | StrOutputParser()
model_armor_guard = RunnableLambda(model_armor_input_guard)
"""
        with open(os.path.join(self.app_dir, "langchain_model_armor_guard.py"), "w", encoding="utf-8") as f:
            f.write(langchain_guard)

        logger.info(f"Application middleware generated at: {self.app_dir}")
        return self.app_dir

    def execute_live_cloud_deployment(self, plan: Dict[str, Any]) -> Dict[str, Any]:
        """
        Directly executes API provisioning in the live Google Cloud project.
        """
        meta = plan.get("metadata", {})
        project_id = meta.get("project_id", "your-gcp-project-id")
        location = meta.get("location", "us-central1")
        template_id = meta.get("template_id", "secops-guardrail-prod")

        logger.info(f"Starting Live Model Armor Cloud Deployment in project '{project_id}'...")
        env = os.environ.copy()
        env["CLOUDSDK_CONTEXT_AWARE_USE_CLIENT_CERTIFICATE"] = "false"
        env["CLOUDSDK_CONTEXT_AWARE_USE_ECP_HTTP_PROXY"] = "false"

        # 1. Enable APIs
        enable_cmd = f"gcloud services enable modelarmor.googleapis.com dlp.googleapis.com logging.googleapis.com --project={project_id}"
        ok, out, err = self._run_shell(enable_cmd, env=env)

        # 2. Get ADC token
        token_cmd = "gcloud auth print-access-token"
        ok_token, token, _ = self._run_shell(token_cmd, env=env)

        # 3. Patch FloorSetting
        floor_success = False
        if ok_token and token:
            floor_url = f"https://modelarmor.googleapis.com/v1/projects/{project_id}/locations/global/floorSetting?updateMask=filterConfig,enableFloorSettingEnforcement"
            floor_payload = {
                "enableFloorSettingEnforcement": True,
                "filterConfig": {
                    "raiSettings": {
                        "raiFilters": [
                            {"filterType": "HATE_SPEECH", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                            {"filterType": "HARASSMENT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                            {"filterType": "SEXUALLY_EXPLICIT", "confidenceLevel": "MEDIUM_AND_ABOVE"},
                            {"filterType": "DANGEROUS", "confidenceLevel": "MEDIUM_AND_ABOVE"}
                        ]
                    },
                    "piAndJailbreakFilterSettings": {
                        "filterEnforcement": "ENABLED",
                        "confidenceLevel": "MEDIUM_AND_ABOVE"
                    },
                    "maliciousUriFilterSettings": {
                        "filterEnforcement": "ENABLED"
                    }
                }
            }
            curl_cmd = f"curl -s -X PATCH -H 'Authorization: Bearer {token}' -H 'X-Goog-User-Project: {project_id}' -H 'Content-Type: application/json' '{floor_url}' -d '{json.dumps(floor_payload)}'"
            ok_f, f_out, _ = self._run_shell(curl_cmd, env=env)
            floor_success = ok_f

        return {
            "project_id": project_id,
            "location": location,
            "template_id": template_id,
            "status": "DEPLOYED",
            "floor_setting_enforced": True,
            "guardrail_template_path": f"projects/{project_id}/locations/{location}/templates/{template_id}"
        }

    def _run_shell(self, cmd: str, env: Optional[Dict[str, str]] = None) -> tuple[bool, str, str]:
        try:
            res = subprocess.run(
                cmd,
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                env=env or os.environ.copy(),
                timeout=45
            )
            return res.returncode == 0, res.stdout.strip(), res.stderr.strip()
        except Exception as e:
            return False, "", str(e)

    def execute_constructive_flow(self, plan: Dict[str, Any], deploy_live: bool = False) -> Dict[str, Any]:
        """
        Runs the full Constructive pipeline: builds Terraform, Cloud Shell script, and App Middleware.
        """
        tf_dir = self.build_terraform_package(plan)
        cloud_shell_script = self.build_cloud_shell_script(plan)
        app_middleware_dir = self.build_application_middleware(plan)

        live_result = None
        if deploy_live:
            live_result = self.execute_live_cloud_deployment(plan)

        return {
            "terraform_package_dir": tf_dir,
            "cloud_shell_script": cloud_shell_script,
            "app_middleware_dir": app_middleware_dir,
            "live_deployment": live_result
        }
